# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AxioFlix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AxioFlix
  pod 'Kingfisher', '~> 4.0'

  target 'AxioFlixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AxioFlixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
